shop : C006.c Contact.o loadD.o printC.o addC.o deleteC.o editC.o searchC.o saveC.o subscribeF.o
	gcc -o shop C006.c Contact.o loadD.o printC.o addC.o deleteC.o editC.o searchC.o saveC.o subscribeF.o
clean : 
	rm *.o shop